CREATE TABLE noteful_folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    foldername TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT,
    folder_id INTEGER REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now(),
    date_modified TIMESTAMP NOT NULL DEFAULT now()
);